export default {
  CITY_ITEMS_NUMBER: 5,
  FETCH_CURRENT_WEATHER_DATA_INTERVAL_MS: 600000, // 10 minutes
  FETCH_WEATHER_FORECAST_DATA_INTERVAL_MS: 3600000, // 60 minutes
  FORECAST_DAYS_NUMBER: 5,
};
